[build-system]
requires = ["setuptools>=61", "wheel", "setuptools_scm"]
build-backend = "setuptools.build_meta"

[project]
name = "umep-reqs"
description = "UMEP requirements package"
authors = [{ name = "UMEP dev team" }]
dependencies = [
    "timezonefinder==6.5.9",
    "supy==2025.7.9.dev0",
    "numba==0.59.0",
    "jaydebeapi==1.2.3",
    "netCDF4",
    "openpyxl",
    "rioxarray",
    "pydantic",
    "target-py"
]
readme = "README.md"
requires-python = ">=3.7"
dynamic = ["version"]

[tool.setuptools]
packages = ["umep-reqs"]

[tool.setuptools_scm]
local_scheme = "no-local-version"
    
# "supy==2025.7.23.dev0", testing without supy