[package]
name = "heimdall-python"
description = "Python bindings for Heimdall"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
homepage.workspace = true
repository.workspace = true
keywords.workspace = true
exclude.workspace = true
readme = "README.md"

[lib]
name = "heimdall_py"
crate-type = ["cdylib"]

[dependencies]
heimdall-decompiler = { workspace = true }
heimdall-common = { workspace = true }
heimdall-core = { workspace = true }
pyo3 = { version = "0.20.0", features = ["extension-module", "abi3-py310"] }
tokio = { workspace = true }
alloy-json-abi = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
bincode = "1.3"
hex = "0.4"
indexmap = { version = "2.0", features = ["serde"] }
tiny-keccak = { version = "2.0", features = ["keccak"] }
storage_layout_extractor = { path = "../../submodules/storage-layout-extractor", default-features = false }
lmdb-rkv = "0.14"
directories-next = "2.0"
blake3 = "1.5"
lazy_static = "1.4"
crossbeam-channel = "0.5"
once_cell = "1.19"
tracing = { workspace = true }
tracing-subscriber = { workspace = true }


[build-dependencies]
pyo3-build-config = "0.20.0"
