[tool.poetry]
name = "pynanomodem"
version = "0.2.7"
description = "A Python implementation for Viasat IoT Nano modems."
authors = ["Your Name <you@example.com>"]
license = "Apache2.0"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pyatcommand = "^0.4.0"

[tool.poetry.group.dev.dependencies]
pytest = "^8.4.0"

[tool.pytest.ini_options]
log_cli = true
log_cli_level = "DEBUG"
log_cli_format = "%(asctime)s,[%(levelname)s],(%(threadName)s),%(module)s.%(funcName)s:%(lineno)s,%(message)s"
log_cli_date_format = "%Y-%m-%d %H:%M:%S"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
