[tool.poetry]
name = "sibi-dst"
version = "2025.9.11"
description = "Data Science Toolkit"
authors = ["Luis Valverde <lvalverdeb@gmail.com>"]
readme = "README.md"
packages = [{ include = "sibi_dst" }]

[tool.poetry.dependencies]
python = ">=3.11,<4.0"
pandas = "^2.3.1"
dask = {extras = ["complete"], version = "^2025.9.0"}
psycopg2 = "^2.9.10"
mysqlclient = "^2.2.7"
webdav4 = "^0.10.0"
clickhouse-connect = "^0.8.18"
clickhouse-driver = "^0.2.9"
tqdm = "^4.67.1"
s3fs = "^2025.5.1"
pydantic = "^2.11.7"
sqlalchemy = "^2.0.41"
pymysql = "^1.1.1"
pyarrow = "^20.0.0"
opentelemetry-exporter-otlp = "^1.35.0"
opentelemetry-sdk = "^1.35.0"
pyiceberg = {extras = ["hive", "s3fs"], version = "^0.9.1"}
sse-starlette = "^3.0.2"
pyrosm = "^0.6.2"
distributed = "^2025.9.1"

[tool.poetry.group.dev]
optional = true

[tool.poetry.group.dev.dependencies]
jupyter = "^1.1.1"
python-dotenv = "^1.1.1"
black = "^25.1.0"

[tool.poetry.group.test]
optional = true

[tool.poetry.group.test.dependencies]
pytest = "^8.4.1"
pytest-cov = "^6.2.1"

[tool.poetry.group.geospatial]
optional = true

[tool.poetry.group.geospatial.dependencies]
osmnx = "^2.0.5"
geopy = "^2.4.1"
folium = "^0.20.0"
geopandas = "^1.1.1"
networkx = "^3.5"
scikit-learn = "^1.7.1"


[tool.poetry.group.loggers.dependencies]
opentelemetry-sdk = "^1.34.1"
opentelemetry-api = "^1.34.1"
opentelemetry-exporter-otlp = "^1.34.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
