[build-system]
requires = ["setuptools>=68", "wheel", "build"]
build-backend = "setuptools.build_meta"

[project]
name = "iatoolkit"
version = "0.3.3"
requires-python = ">=3.10"
description = "IAToolkit"
readme = "readme.md"
license = "MIT"
authors = [{ name = "Fernando Libedinsky" }]

# Si quieres seguir leyendo deps de requirements.txt:
dynamic = ["dependencies"]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
include = ["iatoolkit*", "services*"]

[tool.setuptools.dynamic]
dependencies = { file = ["requirements.txt"] }