[build-system]
requires = ["uv_build>=0.8.2,<0.9.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-root = "src"
source-exclude = ["bin"]
namespace = false

[project]
name = "edc-qol"
version = "1.1.0"
description = "Quality of Life instrument forms/models for the clinicedc/edc and other django projects"
readme = {file = "README.rst", content-type = "text/x-rst"}
license = "GPL-3.0-or-later"
license-files = ["LICEN[CS]E*"]
requires-python = ">=3.12,<3.14"
authors = [
    { name = "Erik van Widenfelt", email = "ew2789@gmail.com" },
]
keywords = [
    "CRF",
    "EQ-5D-3L",
    "Edc",
    "EuroQol",
    "clinical",
    "clinicedc",
    "django",
    "trials",
]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Framework :: Django",
    "Framework :: Django :: 5.2",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
]
dependencies = [
    "clinicedc>=2.0.10",
]

[project.urls]
Homepage = "https://github.com/clinicedc/edc-qol"

[tool.coverage.run]
parallel = false
branch = true
source = ["edc_qol"]

[tool.coverage.paths]
source = ["edc_qol"]

[tool.coverage.report]
show_missing = true
skip_covered = true
omit = ["requirements.txt"]
exclude_lines = [
  "pragma: no cover",
  "if TYPE_CHECKING:",
]

[dependency-groups]
lint = [
    "ruff>=0.12.5",
]

docs = [
    "furo>=2025.7.19",
    "sphinx>=8.2.3",
    "sphinx-design>=0.6.1",
    "sphinx-inline-tabs>=2023.4.21",
]

test = [
    "coverage>=7.10.1",
    "tox-uv>=1.26.2",
    "faker>=37.4.2",
    "model-bakery>=1.20.5",
    "time-machine>=2.16.0",
    "tqdm>=4.67.1",
    "edc-test-settings>=1.1.2",
]

[tool.uv.sources]
edc-csf = { workspace = true }
clinicedc = { path = "../clinicedc", editable = true }
clinicedc-tests = { path = "../clinicedc-tests", editable = true }
edc-test-settings = { path = "../edc-test-settings", editable = true }
