[build-system]
requires = ["setuptools>=45", "pybind11>=2.6.0"]
build-backend = "setuptools.build_meta"

[project]
name = "bigwig_io"
version = "0.0.12"
description = "Read and write bigwig/bigbed files"
authors = [
    {name = "Arthur Gouhier", email = "ajgouhier@gmail.com"}
]
license = "MIT"
requires-python = ">=3.6"
dependencies = [
    "numpy",
    "pybind11>=2.6.0",
]

[tool.setuptools]
zip-safe = false
packages = ["bigwig_io"]
