# pyproject.toml

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
# Map aco package to src directory with subpackages
package-dir = {"aco" = "src"}
packages = ["aco", "aco.cli", "aco.common", "aco.runner", "aco.runner.monkey_patching", "aco.runner.monkey_patching.patches", "aco.server", "aco.server.telemetry"]

[project.scripts]
# Console commands for the agent-copilot package
aco-launch = "aco.cli.aco_launch:main"
aco-config = "aco.cli.aco_config:main"
aco-server = "aco.cli.aco_server:main"

# Let's keep them around for now, aco-launch is confusing 
# when quickly showing the tool.
develop = "aco.cli.aco_launch:main"
server = "aco.cli.aco_server:main"

[tool.black]
line-length = 100

[project]
name = "agops-bird"
version = "0.0.5"
description = "A development tool for LLM call visualization and debugging"
readme = "PKG_README.md"
requires-python = ">=3.10"
license = "GPL-3.0-or-later"
dependencies = ["pyyaml", "dill", "forbiddenfruit", "supabase"]

[project.optional-dependencies]
dev = [
    "black==25.1.0",
    "pytest",
    "pre-commit",
    "responses",
    "openai",
    "anthropic",
    "openai-agents",
    "google-genai"
]

examples = [
    "openai",
    "anthropic", 
    "openai-agents",
    "google-genai"
]
