[project]
name = "pyhom"
version = "1.0.7"
authors = [
  { name="Oscar L. Cruz Gonzalez", email="oscar.lcg93@gmail.com" },
]
description = "PyHom: a Python library for homogenization"
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

dependencies = [
    "requests>=2.20",
    "ruamel.yaml==0.18.6",
    "numpy==1.26.4",
    "scikit-image==0.23.2",
    "sympy==1.12.1",
    "matplotlib==3.9.0",
    "shapely==2.0.4",
    "opencv-python==4.10.0.82",
    "tqdm==4.66.4"
]

[project.urls]
Homepage = "https://github.com/olcruzgonzalez/pyhom"
Issues = "https://github.com/olcruzgonzalez/pyhom/issues"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"