[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "nitrotools"
version = "0.2.0"
description = "A shared library for common utilities."
authors = [
    {name = "Venkatesh Khatri", email = "venkatesh.khatri@gmail.com"},
]
readme = "README.md"
license = "MIT"
license-files = ["LICEN[CS]E*"]
requires-python = ">=3.9"
keywords = ["utilities", "shared", "library"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",

    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
]
dependencies = [
    "python-dotenv",
    "PyYAML",
]

[project.optional-dependencies]
llm = [
    "json-repair",
    "langchain-core",
    "langchain-openai",
    "openai",
]

[project.urls]
Homepage = "https://github.com/introvenk/nitro"
Repository = "https://github.com/introvenk/nitro"
Issues = "https://github.com/introvenk/nitro/issues"



[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q"
testpaths = [
    "tests",
]

[tool.hatch.build.targets.wheel]
exclude = ["venv"]
only-include = ["nitro"]

[tool.hatch.build.targets.sdist]
exclude = ["venv"]
