[tool.pdm]
package-dir = "src"

[project]
name = "microengine-utils"
version = "1.6.0"
description = "Library for Polyswarm Microengine Utility Package"
readme = "README.md"
authors = [
    {name = "PolySwarm Developers", email = "info@polyswarm.io"},
]
classifiers = [
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: Implementation :: PyPy",
]
requires-python = ">=3.10,<4"
dependencies = [
    "datadog>=0.36.0",
    "polyswarm-artifact>=2.2",
    "pydantic>=2.0",
    "requests>=2.32.0",
]
license = "MIT"

[project.urls]
Homepage = "https://github.com/polyswarm/microengine-utils"

[project.optional-dependencies]
tests = [
    "pytest>=8.4.0",
]
content_type = [
    "puremagic",
]
