[project]
name = "pydantic-scrapeable-api-model"
version = "3.1.0"
description = "Minimal utilities to build scrapeable API models on top of Pydantic with simple caching and async HTTP."
readme = "README.md"
authors = [
    { name = "J.I. Cruz", email = "ji@jicruz.com" }
]
requires-python = ">=3.10"
dependencies = [
    "ji-async-http-utils>=5.0.0",
    "pydantic-cacheable-model>=2.0.1",
]

[build-system]
requires = ["uv_build>=0.8.13,<0.9.0"]
build-backend = "uv_build"
