[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "agentflowpy"
version = "0.2.2"
description = "Practial module to build AI agents with context management and step-based execution."
readme = "README.md"
requires-python = ">=3.12"
license = { text = "NonCommercial No-AI License" } 
authors = [
  { name = "Ozel Umut Tam", email = "ozel.umut.tam@gmail.com" }
]
dependencies = [
  "pydantic>=2.11.0"
]

[project.optional-dependencies]
dev = [
  "pytest>=7.0.0",
  "pytest-asyncio>=1.0.0"
  # "isort>=6.0",
  # "flake8>=6.0"
]

[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest.ini_options]
asyncio_mode = "auto"
pythonpath = ["src"]
# [tool.setuptools.include-package-data]
# if you have non-code files to include (e.g. json, templates)
# include = ["some/path", ...]   # optional

# [tool.black]
# line-length = 88
# target-version = ["py310", "py311"]

# [tool.isort]
# profile = "black"
