[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt", "requirements-swh.txt"]}

[project]
name = "sshfs-offline"
version = "0.0.1"
license = { text = "MIT" }
authors = [
    { name="Dave Christenson", email="davechri58@gmail.com" }
]
description = "SSH File System with offline access to cached files."
readme = "README.md"
keywords = ["offline", "cache", "sshfs", "fuse-filesystem", "fuse"]
classifiers = [
  # How mature is this project? Common values are
  #   3 - Alpha
  #   4 - Beta
  #   5 - Production/Stable
  "Development Status :: 4 - Beta",

  # Indicate who your project is intended for
  "Topic :: System :: Filesystems",
  "Development Status :: 4 - Beta",
  "Intended Audience :: Developers",
  "Intended Audience :: End Users/Desktop",
  "Operating System :: MacOS :: MacOS X",
  "Operating System :: POSIX :: Linux",
  "Programming Language :: Python",
  "Programming Language :: Python :: 2.7",
  "Programming Language :: Python :: 3.3",
  "Programming Language :: Python :: 3.4",
  "Programming Language :: Python :: 3.5",
  "Programming Language :: Python :: Implementation :: PyPy",
  "License :: OSI Approved :: MIT License",  
]

[project.scripts]
sshfs-offline = "sshfs_offline.cli:main"
