[project]
name = "coralsnake"
version = "0.0.98"
description = "Transcriptome mapping utils"
authors = [{ name = "Chang Ye", email = "yech1990@gmail.com" }]
requires-python = "~=3.10"
readme = "README.md"
license = "GPL-3.0"
keywords = ["transcriptome", "mapping"]
dependencies = [
  "dnaio>=1.2.1",
  "rich-click>=1.8.3",
  "pysam>=0.22",
  "numpy>=1.26",
  "ncls>=0.0.68",
  "pyfamsa>=0.4",
  "scipy>=1.14",
]

[project.urls]
Repository = "https://github.com/y9c/coralsnake"

[project.scripts]
coralsnake = "coralsnake.cli:cli"

[dependency-groups]
dev = ["setuptools>=70.1.1,<71"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
