[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pysparks"
version = "0.1.1"
description = "Software for Polymerization and Reaction Kinetics Simulations"
authors = [{name = "Devon Callan", email = "devoncallan@ucsb.edu"}]
requires-python = ">=3.10"
dependencies = [
    "numpy",
    "pandas",
    "scipy",
    "matplotlib",
    "tqdm",
    "pyyaml",
    "runkmc==0.1.1",
    "jupyter",
    "notebook",
    "ipykernel",
]
readme = "README.md"
license = {text = "MIT"}

[tool.setuptools.packages.find]
where = ["."]
include = ["sparks*"]

[project.urls]
Homepage = "https://github.com/devoncallan/SPaRKS"
Repository = "https://github.com/devoncallan/SPaRKS"
