[build-system]
requires = ["setuptools>=42","wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
py-modules = []

[project]
name = "pyudon"
version = "0.0.3"
dependencies = [
  "scanpy==1.9.5",
  "numpy==1.24.4",
  "scikit-learn==1.3.0",
  "pandas==2.1.0",
  "nimfa==1.4.0",
  "statsmodels==0.14.0",
  "tqdm==4.66.1",
  "seaborn==0.12.2",
  "matplotlib==3.7.2"
]
requires-python = ">=3.10"
authors = [
  {name = "Kairavee Thakkar", email = "kairavee.thakkar@cchmc.org"},
  {name = "Nathan Salomonis", email = "nathan.salomonis@cchmc.org"}
]
description = "Unsupervised Discovery of Novel Disease Programs"
readme = "README.md"
license = "MIT"
license-files = ["LICEN[CS]E*"]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent"
]

[project.urls]
Repository = "https://github.com/kairaveet/py-udon"
Issues = "https://github.com/kairaveet/py-udon/issues"

[tool.setuptools.packages.find]
where = ["."]