[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "norve"
version = "0.1.0-alpha.1"
authors = [{ name = "LoXewyX" }]
description = "Multi-Source Data Processing Language"
readme = "README.md"
license = { text = "MIT" }
requires-python = ">=3.8"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "Topic :: Software Development :: Interpreters",
    "Topic :: Database",
    "Topic :: Scientific/Engineering :: Information Analysis",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Operating System :: OS Independent",
]
keywords = [
    "json",
    "csv",
    "pipeline",
    "xml",
    "sqlite",
    "excel",
    "declarative",
    "xlsx",
    "xls",
    "db",
    "sqlite3",
    "python-api",
    "lark-parser",
    "dsl-interpreter",
    "multiformat",
]
dependencies = ["lark", "lark-cython", "openpyxl", "pandas"]

[project.optional-dependencies]
dev = ["pytest", "pylint", "setuptools", "twine", "build"]
test = ["pytest"]

[project.scripts]
norvelang = "norve.__main__:main"
norve = "norve.__main__:main"

[project.urls]
Homepage = "https://github.com/LoXewyX/Norvelang"
"Bug Reports" = "https://github.com/LoXewyX/Norvelang/issues"
Source = "https://github.com/LoXewyX/Norvelang"
Documentation = "https://github.com/LoXewyX/Norvelang/blob/main/README.md"

[tool.setuptools.packages.find]
where = ["."]
include = ["norve*"]

[tool.setuptools.package-data]
norve = ["*.lark"]
