# pyproject.toml
[build-system]
requires = ["setuptools>=72", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ds-vault-py-sdk"
version = "v1.0.0.beta.1"
description = "Python SDK for DS Vault - (envelope pattern)"
readme = "README.md"
requires-python = ">=3.12"
license = {text = "Apache-2.0"}
authors = [{name = "Aider AS", email = "hello@grasplabs.no"}]
keywords = ["ds-vault", "envelope-encryption", "sdk", "vault", "ksm"]
classifiers = [
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.12",
  "License :: OSI Approved :: Apache Software License",
  "Operating System :: OS Independent",
  "Typing :: Typed",
]
dependencies = [
  "boto3>=1.40.0,<2",
  "cryptography>=46.0.0,<47",
]

[project.urls]
Homepage = "https://github.com/grasp-labs/ds-vault-py-sdk.git"
Issues = "https://github.com/grasp-labs/ds-vault-py-sdk.git/issues"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
include = ["vault*"]

[project.optional-dependencies]
test = [
  "pytest>=8.3,<9",
  "coverage>=7.10.7,<8"
]
postgres = ["psycopg[binary]>=3.1,<4"]
