[project]
name = "aryn-mcp-server"
version = "0.1.13"
description = "The Official Local Aryn MCP Server"
authors = [
    {name = "Aryn AI",email = "info@aryn.ai"}
]
readme = "README.md"
requires-python = ">=3.12"
license = "Apache-2.0"
license-files = ["LICEN[CS]E*"]
dependencies = [
    "mcp>=1.9.4,<2.0.0",
    "pillow>=11.2.1,<12.0.0",
    "pydantic>=2.11.7,<3.0.0",
    "aryn-sdk>=0.2.12,<0.3.0",
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]

[tool.dxt]
pack = "npx @anthropic-ai/dxt pack"

[build-system]
requires = ["uv_build>=0.7.19,<0.9.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pre-commit>=4.3.0",
    "pytest>=8.4.1",
    "pytest-asyncio>=1.1.0",
    "twine>=6.1.0",
]

[tool.black]
line-length = 120

[tool.mypy]
exclude = ["build"]
ignore_missing_imports = true
explicit_package_bases = true

[project.scripts]
aryn-mcp-server = "aryn_mcp_server.aryn_mcp_server:main"
