[tool.ruff]
line-length = 100

[tool.ruff.lint]
select = ["E", "F"]
ignore = ["E501"]

[project]
name = "mcgt-core"

readme = "README.md"
version = "0.2.6"
[tool.setuptools.dynamic]
version = {attr = "mcgt.__init__.__version__"}
