[build-system]
requires = ["poetry-core>=2.0", "poetry-plugin-freeze"]
build-backend = "poetry.core.masonry.api"


[project]
name = "wmi_dumper"
version = "0.0.0"
description = "Placholder for futur use"
authors = []
license = "MIT"
readme = "README.md"
requires-python = "<4.0,>=3.12"
dependencies = []


[tool.poetry]
packages = [{include = "wmi_dumper", from = "src"}]
