[project]
name = "lxpyodbc"
version = "2.7.202509231353"

requires-python = ">=3.8"
# This is used by the GitHub action that builds release artifacts using cibuildwheel.
# cibuildwheel reads this directly:
#
# https://cibuildwheel.readthedocs.io/en/stable/options/#requires-python

description = "DB API module for ODBC (LX fork)"
readme = "README.md"
license = {text = "MIT-0 License"}

authors = [{name = "Michael Kleehammer", email="michael@kleehammer.com"},
     {name = "leanXcale", email="support@leanxcale.com" }]

maintainers = [{name = 'leanXcale', email="support@leanxcale.com" }]

classifiers=[
    'License :: OSI Approved :: MIT No Attribution License (MIT-0)',
    'Operating System :: Microsoft :: Windows',
    'Operating System :: POSIX',
    'Programming Language :: Python',
    'Programming Language :: Python :: 3',
    'Topic :: Database',
    ]

[project.urls]
"Homepage" = "http://leanxcale.com"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
