[project]
name = "data_driven_test_input_generator"
version = "0.0.3"
authors = [
  { name="Linh Ngoc Le", email="linh.le@tuhh.de" },
]
description = "A Test Input Generation Framework based on Data-Driven Models for Cyber-Physical Systems"
readme = "README.md"
requires-python = ">=3.10,<4.0"
classifiers = [
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "License :: OSI Approved :: BSD License",
  "Operating System :: OS Independent",
  "Topic :: Software Development :: Libraries :: Python Modules",
]

dependencies = [
  "flowcean>=0.4.0.dev0",
  "PyYAML>=6.0.2",
  "river>=0.22.0",
  "scikit-learn>=1.6.1",
  "tabulate>=0.9.0"
]

license = "BSD-3-Clause"
license-files = ["LICEN[CS]E*"]

[project.urls]
Homepage = "https://github.com/flowcean/data-driven-test-input-generator"
Issues = "https://github.com/flowcean/data-driven-test-input-generator/issues"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/ddtig"]

[tool.hatch.build.targets.sdist]
include = ["*.py"]