[build-system]
requires = ["setuptools>=65.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "az-smart-logger"
version = "1.0.0"
description = "Smart Logger library for Python projects with FastAPI, Flask, and Django support"
readme = "README.md"
requires-python = ">=3.8"
license = { text = "MIT" }
authors = [
    { name = "Shahabaz Alam", email = "shahabazalam1@gmail.com" }
]
dependencies = [
    "annotated-types==0.7.0",
    "anyio==4.10.0",
    "argon2-cffi==25.1.0",
    "argon2-cffi-bindings==25.1.0",
    "cffi==2.0.0",
    "click==8.2.1",
    "fastapi==0.116.1",
    "h11==0.16.0",
    "httptools==0.6.4",
    "idna==3.10",
    "Jinja2==3.1.6",
    "markdown-it-py==4.0.0",
    "MarkupSafe==3.0.2",
    "mdurl==0.1.2",
    "passlib==1.7.4",
    "pycparser==2.23",
    "pydantic==2.11.7",
    "pydantic_core==2.33.2",
    "Pygments==2.19.2",
    "PyJWT==2.10.1",
    "python-dotenv==1.1.1",
    "PyYAML==6.0.2",
    "rich==14.1.0",
    "shellingham==1.5.4",
    "sniffio==1.3.1",
    "SQLAlchemy==2.0.43",
    "typer==0.17.4",
    "typing_extensions==4.15.0",
    "typing-inspection==0.4.1",
    "uvicorn[standard]>=0.23.0",
    "uvloop==0.21.0",
    "watchfiles==1.1.0",
    "websockets==15.0.1",
    "psutil==7.1.0",
    "python-socketio[asyncio_server]==5.13.0"
]

[project.scripts]
smart-logger = "smart_logger.cli.commands:main"

[tool.setuptools.packages.find]
exclude = ["tests", "examples"]

[tool.setuptools]
include-package-data = true