[project]
name = "netbox-routing-complex"
version = "0.2.84"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django-tables2>=2.7.5",
]

#added this so that the html files would be packaged in the build process
[tool.setuptools.package-data]
"netbox_routing_complex" = ["templates/**/*.html"]