[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "sagarcustompackage"   # must be unique on PyPI
version = "0.1.1"
description = "Reusable helpers for OTP, JWT authentication, and JSON serialization and Global patch for Python requests to allow TLSv1.2 with lower SECLEVEL"
readme = "README.md"
license = "MIT"
authors = [
  { name = "Sagar Sonara", email = "sagarsonara2143@gmail.com" }
]
dependencies = [
    "pyjwt>=2.0.0",
    "requests>=2.25.0",
    "urllib3>=2.0.0"
]
requires-python = ">=3.8"

[project.urls]
Homepage = "https://github.com/Sagarsonara2143/PyPi_CustomPackage"


[tool.setuptools]
packages = ["common_helper"]
