[build-system]
requires = ["hatchling>=1.27.0"]
build-backend = "hatchling.build"

[project]
name = "deph"
dynamic = ["version"]
description = "A developer utility to isolate, analyze, and compose Python code dependencies."
readme = "README.md"
license = "MIT"
authors = [{ name = "SungHo Lee", email = "shlee@unc.edu" }]
maintainers = [{ name = "SungHo Lee", email = "shlee@unc.edu" }]
keywords = ["dependency", "analysis", "isolation", "ast", "import"]
classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: MIT License",
  "Environment :: Console"
]
requires-python = ">=3.9"
dependencies = ["requests"]

[project.urls]
Homepage = "https://github.com/dvm-shlee/deph"

[tool.hatch.version]
path = "src/deph/__init__.py"
style = "pep440"

[tool.hatch.build]
sources = ["src"]

[tool.hatch.build.targets.sdist]
include = ["src", "LICENSE", "README.md", "tests"]

[tool.hatch.build.targets.wheel]
packages = ["src/deph", "src/devh", "src/fmth"]
artifacts = ["LICENSE"]

[tool.pytest.ini_options]
log_cli = true
log_cli_level = "DEBUG"
