[project]
name = "spssio"
version = "0.2.4"
description = "Pythonic, fast access to SPSS files"
readme = "README.md"
authors = [
    { name = "Jose Tiago Macara Coutinho", email = "coutinhotiago@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "numpy"
]

[build-system]
requires = ["uv_build>=0.8.12,<0.9.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=8.4.1,<9",
    "pytest-cov>=7.0.0",
]
