[build-system]
requires = ["hatchling >= 1.26"]
build-backend = "hatchling.build"

[project]
name = "mediaComp"
version = "0.4.2"
dependencies = [
  "wxPython > 4.2.0",
  "pillow >11.0.0",
  "pygame > 2.5.0",
  "matplotlib >= 3.10.0",
  "numpy >= 2.2.1",
  "sounddevice >= 0.5.2",
]
authors = [
  { name="A community project", email="dllargent@bsu.edu" },
]

description = "A multimedia processing library for Python 3."
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = "GPL-3.0-or-later"
license-files = ["LICEN[CS]E*"]

[project.urls]
Homepage = "https://github.com/dllargent/mediaComp"
Issues = "https://github.com/dllargent/mediaComp/issues"

[tool.setuptools.package-data]
"mediaComp" = ["py.typed", "*.pyi"]

[tool.hatch.build.targets.sdist]
exclude = [
  "*.docx",
  "**/__pycache__",
  "test.py",
  "dev/",
  "dialog/"
]