[build-system]
requires = [
    "setuptools>=61.0",
    "wheel"
]
build-backend = "setuptools.build_meta"

[project]
name = "pykoolbox"
version = "0.3.19"
authors = [
  { name="Klim Naidenov", email="knaydenov@yandex.ru" },
]
description = "An advanced entrypoint. It contains various tools helping set up environment and run tasks"
readme = "README.md"
requires-python = ">=3.0"
classifiers = [
    "Operating System :: OS Independent",
]

[tool.setuptools.package-data]
koolbox = ["bin/*"]

[project.scripts]
koolbox = "koolbox.koolbox:main"

[project.urls]
Homepage = "https://git@git.sourcecraft.dev/0x4b4c494d/pykoolbox.git"
Issues = "https://sourcecraft.dev/0x4b4c494d/pykoolbox/issues"